'------------------------------------------------------------------------------
'  <auto-generated>
'      Этот код был создан построителем кодированных тестов ИП.
'      Версия: 16.0.0.0
'
'      Изменения, внесенные в этот файл, могут привести к неправильной работе кода и будут
'      утрачены при повторном формировании кода.
'  </auto-generated>
' ------------------------------------------------------------------------------

Imports System
Imports System.CodeDom.Compiler
Imports System.Collections.Generic
Imports System.Drawing
Imports System.Text.RegularExpressions
Imports System.Windows.Input
Imports Microsoft.VisualStudio.TestTools.UITest.Extension
Imports Microsoft.VisualStudio.TestTools.UITesting
Imports Microsoft.VisualStudio.TestTools.UITesting.WinControls
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard
Imports Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse
Imports MouseButtons = System.Windows.Forms.MouseButtons

Namespace CodedUITestProject
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Partial Public Class UIMap
        
        '''<summary>
        '''RecordedMethod1 - Используйте "RecordedMethod1Params" для передачи параметров в этот метод.
        '''</summary>
        Public Sub RecordedMethod1()
            Dim uIИмяEdit As WinEdit = Me.UIDebugWindow.UIItemWindow.UIProject7exeListItem.UIИмяEdit
            Dim uIProject7exeListItem As WinListItem = Me.UIDebugWindow.UIItemWindow.UIПросмотрэлементовList.UIProject7exeListItem
            Dim uIEditwithPhpStormMenuItem As WinMenuItem = Me.UIItemWindow.UIКонтекстMenu.UIEditwithPhpStormMenuItem
            Dim uIВвестиWindow As WinWindow = Me.UIТестированиеПОWindow.UIТестированиеПОClient.UIВвестиWindow
            Dim uINumericUpDown1ComboBox As WinComboBox = Me.UIТестированиеПОWindow.UINumericUpDown1Window.UINumericUpDown1ComboBox
            Dim uIПосчитатьWindow As WinWindow = Me.UIТестированиеПОWindow.UIТестированиеПОClient.UIПосчитатьWindow

            'Щелкните "Имя" надпись
            Mouse.Click(uIИмяEdit, New Point(37, 22))

            'Щелкните "Имя" надпись
            Mouse.Click(uIИмяEdit, New Point(37, 22))

            'Щелкните "Project7.exe" элемент списка
            Mouse.Click(uIProject7exeListItem, New Point(190, 21))

            'Щелкните "Имя" надпись
            Mouse.Click(uIИмяEdit, New Point(162, 21))

            'Щелкните "Project7.exe" элемент списка
            Mouse.Click(uIProject7exeListItem, New Point(190, 21))

            'Правая-Щелкните "Имя" надпись
            Mouse.Click(uIИмяEdit, MouseButtons.Right, ModifierKeys.None, New Point(48, 15))

            'Щелкните "Edit with PhpStorm" элемент меню
            Mouse.Click(uIEditwithPhpStormMenuItem, New Point(193, 3))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(115, 54))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(115, 54))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(115, 54))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(115, 54))

            'Выберите "77" в "numericUpDown1" поле со списком
            uINumericUpDown1ComboBox.EditableItem = Me.RecordedMethod1Params.UINumericUpDown1ComboBoxEditableItem

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(98, 53))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(98, 53))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(98, 53))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(98, 53))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(98, 53))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(98, 53))

            'Щелкните "Посчитать" окно
            Mouse.Click(uIПосчитатьWindow, New Point(100, 54))
        End Sub
        
        '''<summary>
        '''RecordedMethod2
        '''</summary>
        Public Sub RecordedMethod2()
            Dim uIВвестиWindow As WinWindow = Me.UIТестированиеПОWindow.UIТестированиеПОClient.UIВвестиWindow
            Dim uIПосчитатьWindow As WinWindow = Me.UIТестированиеПОWindow.UIТестированиеПОClient.UIПосчитатьWindow
            Dim uIОКButton As WinButton = Me.UIОКWindow.UIОКButton

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(120, 79))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(120, 79))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(120, 79))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(120, 79))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(120, 79))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(120, 79))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(120, 79))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(120, 79))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(120, 79))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(120, 79))

            'Щелкните "Посчитать" окно
            Mouse.Click(uIПосчитатьWindow, New Point(123, 75))

            'Щелкните "ОК" кнопка
            Mouse.Click(uIОКButton, New Point(28, 19))
        End Sub
        
        #Region "Properties"
        Public Overridable ReadOnly Property RecordedMethod1Params() As RecordedMethod1Params
            Get
                If (Me.mRecordedMethod1Params Is Nothing) Then
                    Me.mRecordedMethod1Params = New RecordedMethod1Params()
                End If
                Return Me.mRecordedMethod1Params
            End Get
        End Property
        
        Public ReadOnly Property UIDebugWindow() As UIDebugWindow
            Get
                If (Me.mUIDebugWindow Is Nothing) Then
                    Me.mUIDebugWindow = New UIDebugWindow()
                End If
                Return Me.mUIDebugWindow
            End Get
        End Property
        
        Public ReadOnly Property UIItemWindow() As UIItemWindow1
            Get
                If (Me.mUIItemWindow Is Nothing) Then
                    Me.mUIItemWindow = New UIItemWindow1()
                End If
                Return Me.mUIItemWindow
            End Get
        End Property
        
        Public ReadOnly Property UIТестированиеПОWindow() As UIТестированиеПОWindow
            Get
                If (Me.mUIТестированиеПОWindow Is Nothing) Then
                    Me.mUIТестированиеПОWindow = New UIТестированиеПОWindow()
                End If
                Return Me.mUIТестированиеПОWindow
            End Get
        End Property
        
        Public ReadOnly Property UIОКWindow() As UIОКWindow
            Get
                If (Me.mUIОКWindow Is Nothing) Then
                    Me.mUIОКWindow = New UIОКWindow()
                End If
                Return Me.mUIОКWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mRecordedMethod1Params As RecordedMethod1Params
        
        Private mUIDebugWindow As UIDebugWindow
        
        Private mUIItemWindow As UIItemWindow1
        
        Private mUIТестированиеПОWindow As UIТестированиеПОWindow
        
        Private mUIОКWindow As UIОКWindow
        #End Region
    End Class
    
    '''<summary>
    '''Параметры для передачи в "RecordedMethod1"
    '''</summary>
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class RecordedMethod1Params
        
        #Region "Fields"
        '''<summary>
        '''Выберите "77" в "numericUpDown1" поле со списком
        '''</summary>
        Public UINumericUpDown1ComboBoxEditableItem As String = "77"
        #End Region
    End Class
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class UIDebugWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "Debug"
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "CabinetWClass"
            Me.WindowTitles.Add("Debug")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIItemWindow() As UIItemWindow
            Get
                If (Me.mUIItemWindow Is Nothing) Then
                    Me.mUIItemWindow = New UIItemWindow(Me)
                End If
                Return Me.mUIItemWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIItemWindow As UIItemWindow
        #End Region
    End Class
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class UIItemWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.AccessibleName) = "Просмотр элементов"
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "DirectUIHWND"
            Me.WindowTitles.Add("Debug")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIProject7exeListItem() As UIProject7exeListItem
            Get
                If (Me.mUIProject7exeListItem Is Nothing) Then
                    Me.mUIProject7exeListItem = New UIProject7exeListItem(Me)
                End If
                Return Me.mUIProject7exeListItem
            End Get
        End Property
        
        Public ReadOnly Property UIПросмотрэлементовList() As UIПросмотрэлементовList
            Get
                If (Me.mUIПросмотрэлементовList Is Nothing) Then
                    Me.mUIПросмотрэлементовList = New UIПросмотрэлементовList(Me)
                End If
                Return Me.mUIПросмотрэлементовList
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIProject7exeListItem As UIProject7exeListItem
        
        Private mUIПросмотрэлементовList As UIПросмотрэлементовList
        #End Region
    End Class
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class UIProject7exeListItem
        Inherits WinListItem
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinListItem.PropertyNames.Name) = "Project7.exe"
            Me.WindowTitles.Add("Debug")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIИмяEdit() As WinEdit
            Get
                If (Me.mUIИмяEdit Is Nothing) Then
                    Me.mUIИмяEdit = New WinEdit(Me)
                    Me.mUIИмяEdit.SearchProperties(WinEdit.PropertyNames.Name) = "Имя"
                    Me.mUIИмяEdit.WindowTitles.Add("Debug")
                End If
                Return Me.mUIИмяEdit
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIИмяEdit As WinEdit
        #End Region
    End Class
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class UIПросмотрэлементовList
        Inherits WinList
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinList.PropertyNames.Name) = "Просмотр элементов"
            Me.WindowTitles.Add("Debug")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIProject7exeListItem() As WinListItem
            Get
                If (Me.mUIProject7exeListItem Is Nothing) Then
                    Me.mUIProject7exeListItem = New WinListItem(Me)
                    Me.mUIProject7exeListItem.SearchProperties(WinListItem.PropertyNames.Name) = "Project7.exe"
                    Me.mUIProject7exeListItem.WindowTitles.Add("Debug")
                End If
                Return Me.mUIProject7exeListItem
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIProject7exeListItem As WinListItem
        #End Region
    End Class
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class UIItemWindow1
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.AccessibleName) = "Контекст"
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "#32768"
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIКонтекстMenu() As UIКонтекстMenu
            Get
                If (Me.mUIКонтекстMenu Is Nothing) Then
                    Me.mUIКонтекстMenu = New UIКонтекстMenu(Me)
                End If
                Return Me.mUIКонтекстMenu
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIКонтекстMenu As UIКонтекстMenu
        #End Region
    End Class
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class UIКонтекстMenu
        Inherits WinMenu
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinMenu.PropertyNames.Name) = "Контекст"
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIEditwithPhpStormMenuItem() As WinMenuItem
            Get
                If (Me.mUIEditwithPhpStormMenuItem Is Nothing) Then
                    Me.mUIEditwithPhpStormMenuItem = New WinMenuItem(Me)
                    Me.mUIEditwithPhpStormMenuItem.SearchProperties(WinMenuItem.PropertyNames.Name) = "Edit with PhpStorm"
                End If
                Return Me.mUIEditwithPhpStormMenuItem
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIEditwithPhpStormMenuItem As WinMenuItem
        #End Region
    End Class
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class UIТестированиеПОWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "Тестирование ПО"
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains))
            Me.WindowTitles.Add("Тестирование ПО")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIТестированиеПОClient() As UIТестированиеПОClient
            Get
                If (Me.mUIТестированиеПОClient Is Nothing) Then
                    Me.mUIТестированиеПОClient = New UIТестированиеПОClient(Me)
                End If
                Return Me.mUIТестированиеПОClient
            End Get
        End Property
        
        Public ReadOnly Property UINumericUpDown1Window() As UINumericUpDown1Window
            Get
                If (Me.mUINumericUpDown1Window Is Nothing) Then
                    Me.mUINumericUpDown1Window = New UINumericUpDown1Window(Me)
                End If
                Return Me.mUINumericUpDown1Window
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIТестированиеПОClient As UIТестированиеПОClient
        
        Private mUINumericUpDown1Window As UINumericUpDown1Window
        #End Region
    End Class
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class UIТестированиеПОClient
        Inherits WinClient
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinControl.PropertyNames.Name) = "Тестирование ПО"
            Me.WindowTitles.Add("Тестирование ПО")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIВвестиWindow() As WinWindow
            Get
                If (Me.mUIВвестиWindow Is Nothing) Then
                    Me.mUIВвестиWindow = New WinWindow(Me)
                    Me.mUIВвестиWindow.SearchProperties(WinWindow.PropertyNames.Name) = "Ввести"
                    Me.mUIВвестиWindow.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains))
                    Me.mUIВвестиWindow.WindowTitles.Add("Тестирование ПО")
                End If
                Return Me.mUIВвестиWindow
            End Get
        End Property
        
        Public ReadOnly Property UIПосчитатьWindow() As WinWindow
            Get
                If (Me.mUIПосчитатьWindow Is Nothing) Then
                    Me.mUIПосчитатьWindow = New WinWindow(Me)
                    Me.mUIПосчитатьWindow.SearchProperties(WinWindow.PropertyNames.Name) = "Посчитать"
                    Me.mUIПосчитатьWindow.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains))
                    Me.mUIПосчитатьWindow.WindowTitles.Add("Тестирование ПО")
                End If
                Return Me.mUIПосчитатьWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIВвестиWindow As WinWindow
        
        Private mUIПосчитатьWindow As WinWindow
        #End Region
    End Class
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class UINumericUpDown1Window
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "numericUpDown1"
            Me.WindowTitles.Add("Тестирование ПО")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UINumericUpDown1ComboBox() As WinComboBox
            Get
                If (Me.mUINumericUpDown1ComboBox Is Nothing) Then
                    Me.mUINumericUpDown1ComboBox = New WinComboBox(Me)
                    Me.mUINumericUpDown1ComboBox.WindowTitles.Add("Тестирование ПО")
                End If
                Return Me.mUINumericUpDown1ComboBox
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUINumericUpDown1ComboBox As WinComboBox
        #End Region
    End Class
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class UIОКWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "ОК"
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "Button"
            Me.WindowTitles.Add("ОК")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIОКButton() As WinButton
            Get
                If (Me.mUIОКButton Is Nothing) Then
                    Me.mUIОКButton = New WinButton(Me)
                    Me.mUIОКButton.SearchProperties(WinButton.PropertyNames.Name) = "ОК"
                    Me.mUIОКButton.WindowTitles.Add("ОК")
                End If
                Return Me.mUIОКButton
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIОКButton As WinButton
        #End Region
    End Class
End Namespace
