'------------------------------------------------------------------------------
'  <auto-generated>
'      Этот код был создан построителем кодированных тестов ИП.
'      Версия: 16.0.0.0
'
'      Изменения, внесенные в этот файл, могут привести к неправильной работе кода и будут
'      утрачены при повторном формировании кода.
'  </auto-generated>
' ------------------------------------------------------------------------------

Imports System
Imports System.CodeDom.Compiler
Imports System.Collections.Generic
Imports System.Drawing
Imports System.Text.RegularExpressions
Imports System.Windows.Input
Imports Microsoft.VisualStudio.TestTools.UITest.Extension
Imports Microsoft.VisualStudio.TestTools.UITesting
Imports Microsoft.VisualStudio.TestTools.UITesting.WinControls
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard
Imports Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse
Imports MouseButtons = System.Windows.Forms.MouseButtons

Namespace CodedUITestProject7
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Partial Public Class UIMap
        
        '''<summary>
        '''RecordedMethod1 - Используйте "RecordedMethod1Params" для передачи параметров в этот метод.
        '''</summary>
        Public Sub RecordedMethod1()
            Dim uINumericUpDown1ComboBox As WinComboBox = Me.UIТестированиеПОWindow.UINumericUpDown1Window.UINumericUpDown1ComboBox
            Dim uIВвестиWindow As WinWindow = Me.UIТестированиеПОWindow.UIТестированиеПОClient.UIВвестиWindow
            Dim uIОКButton As WinButton = Me.UIОКWindow.UIОКButton
            Dim uIПосчитатьWindow As WinWindow = Me.UIТестированиеПОWindow.UIТестированиеПОClient.UIПосчитатьWindow
            Dim uIОчиститьвсеWindow As WinWindow = Me.UIТестированиеПОWindow.UIТестированиеПОClient.UIОчиститьвсеWindow

            'Запуск "%USERPROFILE%\source\repos\Project7\Debug\Project7.exe"
            Dim uIТестированиеПОWindow As ApplicationUnderTest = ApplicationUnderTest.Launch(Me.RecordedMethod1Params.UIТестированиеПОWindowExePath, Me.RecordedMethod1Params.UIТестированиеПОWindowAlternateExePath)

            'Выберите "77" в "numericUpDown1" поле со списком
            uINumericUpDown1ComboBox.EditableItem = Me.RecordedMethod1Params.UINumericUpDown1ComboBoxEditableItem

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(84, 61))

            'Выберите "777777" в "numericUpDown1" поле со списком
            uINumericUpDown1ComboBox.EditableItem = Me.RecordedMethod1Params.UINumericUpDown1ComboBoxEditableItem1

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(81, 57))

            'Тип "{Enter}" в "ОК" кнопка
            Keyboard.SendKeys(uIОКButton, Me.RecordedMethod1Params.UIОКButtonSendKeys, ModifierKeys.None)

            'Выберите "0" в "numericUpDown1" поле со списком
            uINumericUpDown1ComboBox.EditableItem = Me.RecordedMethod1Params.UINumericUpDown1ComboBoxEditableItem2

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(89, 64))

            'Выберите "-2" в "numericUpDown1" поле со списком
            uINumericUpDown1ComboBox.EditableItem = Me.RecordedMethod1Params.UINumericUpDown1ComboBoxEditableItem3

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(77, 60))

            'Тип "{Enter}" в "ОК" кнопка
            Keyboard.SendKeys(uIОКButton, Me.RecordedMethod1Params.UIОКButtonSendKeys1, ModifierKeys.None)

            'Выберите "100" в "numericUpDown1" поле со списком
            uINumericUpDown1ComboBox.EditableItem = Me.RecordedMethod1Params.UINumericUpDown1ComboBoxEditableItem4

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(86, 55))

            'Выберите "101" в "numericUpDown1" поле со списком
            uINumericUpDown1ComboBox.EditableItem = Me.RecordedMethod1Params.UINumericUpDown1ComboBoxEditableItem5

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(117, 57))

            'Выберите "102" в "numericUpDown1" поле со списком
            uINumericUpDown1ComboBox.EditableItem = Me.RecordedMethod1Params.UINumericUpDown1ComboBoxEditableItem6

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(92, 59))

            'Выберите "103" в "numericUpDown1" поле со списком
            uINumericUpDown1ComboBox.EditableItem = Me.RecordedMethod1Params.UINumericUpDown1ComboBoxEditableItem7

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(75, 59))

            'Выберите "104" в "numericUpDown1" поле со списком
            uINumericUpDown1ComboBox.EditableItem = Me.RecordedMethod1Params.UINumericUpDown1ComboBoxEditableItem8

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(98, 58))

            'Выберите "105" в "numericUpDown1" поле со списком
            uINumericUpDown1ComboBox.EditableItem = Me.RecordedMethod1Params.UINumericUpDown1ComboBoxEditableItem9

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(89, 60))

            'Выберите "106" в "numericUpDown1" поле со списком
            uINumericUpDown1ComboBox.EditableItem = Me.RecordedMethod1Params.UINumericUpDown1ComboBoxEditableItem10

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(132, 54))

            'Выберите "107" в "numericUpDown1" поле со списком
            uINumericUpDown1ComboBox.EditableItem = Me.RecordedMethod1Params.UINumericUpDown1ComboBoxEditableItem11

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(105, 56))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(86, 63))

            'Тип "{Enter}" в "ОК" кнопка
            Keyboard.SendKeys(uIОКButton, Me.RecordedMethod1Params.UIОКButtonSendKeys2, ModifierKeys.None)

            'Щелкните "Посчитать" окно
            Mouse.Click(uIПосчитатьWindow, New Point(110, 59))

            'Щелкните "Очистить все" окно
            Mouse.Click(uIОчиститьвсеWindow, New Point(139, 65))
        End Sub
        
        #Region "Properties"
        Public Overridable ReadOnly Property RecordedMethod1Params() As RecordedMethod1Params
            Get
                If (Me.mRecordedMethod1Params Is Nothing) Then
                    Me.mRecordedMethod1Params = New RecordedMethod1Params()
                End If
                Return Me.mRecordedMethod1Params
            End Get
        End Property
        
        Public ReadOnly Property UIТестированиеПОWindow() As UIТестированиеПОWindow
            Get
                If (Me.mUIТестированиеПОWindow Is Nothing) Then
                    Me.mUIТестированиеПОWindow = New UIТестированиеПОWindow()
                End If
                Return Me.mUIТестированиеПОWindow
            End Get
        End Property
        
        Public ReadOnly Property UIОКWindow() As UIОКWindow
            Get
                If (Me.mUIОКWindow Is Nothing) Then
                    Me.mUIОКWindow = New UIОКWindow()
                End If
                Return Me.mUIОКWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mRecordedMethod1Params As RecordedMethod1Params
        
        Private mUIТестированиеПОWindow As UIТестированиеПОWindow
        
        Private mUIОКWindow As UIОКWindow
        #End Region
    End Class
    
    '''<summary>
    '''Параметры для передачи в "RecordedMethod1"
    '''</summary>
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class RecordedMethod1Params
        
        #Region "Fields"
        '''<summary>
        '''Запуск "%USERPROFILE%\source\repos\Project7\Debug\Project7.exe"
        '''</summary>
        Public UIТестированиеПОWindowExePath As String = "C:\Users\mihan\source\repos\Project7\Debug\Project7.exe"
        
        '''<summary>
        '''Запуск "%USERPROFILE%\source\repos\Project7\Debug\Project7.exe"
        '''</summary>
        Public UIТестированиеПОWindowAlternateExePath As String = "%USERPROFILE%\source\repos\Project7\Debug\Project7.exe"
        
        '''<summary>
        '''Выберите "77" в "numericUpDown1" поле со списком
        '''</summary>
        Public UINumericUpDown1ComboBoxEditableItem As String = "77"
        
        '''<summary>
        '''Выберите "777777" в "numericUpDown1" поле со списком
        '''</summary>
        Public UINumericUpDown1ComboBoxEditableItem1 As String = "777777"
        
        '''<summary>
        '''Тип "{Enter}" в "ОК" кнопка
        '''</summary>
        Public UIОКButtonSendKeys As String = "{Enter}"
        
        '''<summary>
        '''Выберите "0" в "numericUpDown1" поле со списком
        '''</summary>
        Public UINumericUpDown1ComboBoxEditableItem2 As String = "0"
        
        '''<summary>
        '''Выберите "-2" в "numericUpDown1" поле со списком
        '''</summary>
        Public UINumericUpDown1ComboBoxEditableItem3 As String = "-2"
        
        '''<summary>
        '''Тип "{Enter}" в "ОК" кнопка
        '''</summary>
        Public UIОКButtonSendKeys1 As String = "{Enter}"
        
        '''<summary>
        '''Выберите "100" в "numericUpDown1" поле со списком
        '''</summary>
        Public UINumericUpDown1ComboBoxEditableItem4 As String = "100"
        
        '''<summary>
        '''Выберите "101" в "numericUpDown1" поле со списком
        '''</summary>
        Public UINumericUpDown1ComboBoxEditableItem5 As String = "101"
        
        '''<summary>
        '''Выберите "102" в "numericUpDown1" поле со списком
        '''</summary>
        Public UINumericUpDown1ComboBoxEditableItem6 As String = "102"
        
        '''<summary>
        '''Выберите "103" в "numericUpDown1" поле со списком
        '''</summary>
        Public UINumericUpDown1ComboBoxEditableItem7 As String = "103"
        
        '''<summary>
        '''Выберите "104" в "numericUpDown1" поле со списком
        '''</summary>
        Public UINumericUpDown1ComboBoxEditableItem8 As String = "104"
        
        '''<summary>
        '''Выберите "105" в "numericUpDown1" поле со списком
        '''</summary>
        Public UINumericUpDown1ComboBoxEditableItem9 As String = "105"
        
        '''<summary>
        '''Выберите "106" в "numericUpDown1" поле со списком
        '''</summary>
        Public UINumericUpDown1ComboBoxEditableItem10 As String = "106"
        
        '''<summary>
        '''Выберите "107" в "numericUpDown1" поле со списком
        '''</summary>
        Public UINumericUpDown1ComboBoxEditableItem11 As String = "107"
        
        '''<summary>
        '''Тип "{Enter}" в "ОК" кнопка
        '''</summary>
        Public UIОКButtonSendKeys2 As String = "{Enter}"
        #End Region
    End Class
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class UIТестированиеПОWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "Тестирование ПО"
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains))
            Me.WindowTitles.Add("Тестирование ПО")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UINumericUpDown1Window() As UINumericUpDown1Window
            Get
                If (Me.mUINumericUpDown1Window Is Nothing) Then
                    Me.mUINumericUpDown1Window = New UINumericUpDown1Window(Me)
                End If
                Return Me.mUINumericUpDown1Window
            End Get
        End Property
        
        Public ReadOnly Property UIТестированиеПОClient() As UIТестированиеПОClient
            Get
                If (Me.mUIТестированиеПОClient Is Nothing) Then
                    Me.mUIТестированиеПОClient = New UIТестированиеПОClient(Me)
                End If
                Return Me.mUIТестированиеПОClient
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUINumericUpDown1Window As UINumericUpDown1Window
        
        Private mUIТестированиеПОClient As UIТестированиеПОClient
        #End Region
    End Class
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class UINumericUpDown1Window
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "numericUpDown1"
            Me.WindowTitles.Add("Тестирование ПО")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UINumericUpDown1ComboBox() As WinComboBox
            Get
                If (Me.mUINumericUpDown1ComboBox Is Nothing) Then
                    Me.mUINumericUpDown1ComboBox = New WinComboBox(Me)
                    Me.mUINumericUpDown1ComboBox.WindowTitles.Add("Тестирование ПО")
                End If
                Return Me.mUINumericUpDown1ComboBox
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUINumericUpDown1ComboBox As WinComboBox
        #End Region
    End Class
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class UIТестированиеПОClient
        Inherits WinClient
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinControl.PropertyNames.Name) = "Тестирование ПО"
            Me.WindowTitles.Add("Тестирование ПО")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIВвестиWindow() As WinWindow
            Get
                If (Me.mUIВвестиWindow Is Nothing) Then
                    Me.mUIВвестиWindow = New WinWindow(Me)
                    Me.mUIВвестиWindow.SearchProperties(WinWindow.PropertyNames.Name) = "Ввести"
                    Me.mUIВвестиWindow.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains))
                    Me.mUIВвестиWindow.WindowTitles.Add("Тестирование ПО")
                End If
                Return Me.mUIВвестиWindow
            End Get
        End Property
        
        Public ReadOnly Property UIПосчитатьWindow() As WinWindow
            Get
                If (Me.mUIПосчитатьWindow Is Nothing) Then
                    Me.mUIПосчитатьWindow = New WinWindow(Me)
                    Me.mUIПосчитатьWindow.SearchProperties(WinWindow.PropertyNames.Name) = "Посчитать"
                    Me.mUIПосчитатьWindow.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains))
                    Me.mUIПосчитатьWindow.WindowTitles.Add("Тестирование ПО")
                End If
                Return Me.mUIПосчитатьWindow
            End Get
        End Property
        
        Public ReadOnly Property UIОчиститьвсеWindow() As WinWindow
            Get
                If (Me.mUIОчиститьвсеWindow Is Nothing) Then
                    Me.mUIОчиститьвсеWindow = New WinWindow(Me)
                    Me.mUIОчиститьвсеWindow.SearchProperties(WinWindow.PropertyNames.Name) = "Очистить все"
                    Me.mUIОчиститьвсеWindow.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains))
                    Me.mUIОчиститьвсеWindow.WindowTitles.Add("Тестирование ПО")
                End If
                Return Me.mUIОчиститьвсеWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIВвестиWindow As WinWindow
        
        Private mUIПосчитатьWindow As WinWindow
        
        Private mUIОчиститьвсеWindow As WinWindow
        #End Region
    End Class
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class UIОКWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "ОК"
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "Button"
            Me.WindowTitles.Add("ОК")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIОКButton() As WinButton
            Get
                If (Me.mUIОКButton Is Nothing) Then
                    Me.mUIОКButton = New WinButton(Me)
                    Me.mUIОКButton.SearchProperties(WinButton.PropertyNames.Name) = "ОК"
                    Me.mUIОКButton.WindowTitles.Add("ОК")
                End If
                Return Me.mUIОКButton
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIОКButton As WinButton
        #End Region
    End Class
End Namespace
