'------------------------------------------------------------------------------
'  <auto-generated>
'      Этот код был создан построителем кодированных тестов ИП.
'      Версия: 16.0.0.0
'
'      Изменения, внесенные в этот файл, могут привести к неправильной работе кода и будут
'      утрачены при повторном формировании кода.
'  </auto-generated>
' ------------------------------------------------------------------------------

Imports System
Imports System.CodeDom.Compiler
Imports System.Collections.Generic
Imports System.Drawing
Imports System.Text.RegularExpressions
Imports System.Windows.Input
Imports Microsoft.VisualStudio.TestTools.UITest.Extension
Imports Microsoft.VisualStudio.TestTools.UITesting
Imports Microsoft.VisualStudio.TestTools.UITesting.WinControls
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard
Imports Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse
Imports MouseButtons = System.Windows.Forms.MouseButtons

Namespace CodedUITestProject2
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Partial Public Class UIMap
        
        '''<summary>
        '''RecordedMethod1 - Используйте "RecordedMethod1Params" для передачи параметров в этот метод.
        '''</summary>
        Public Sub RecordedMethod1()
            Dim uIВвестиWindow As WinWindow = Me.UIТестированиеПОWindow.UIТестированиеПОClient.UIВвестиWindow
            Dim uINumericUpDown1ComboBox As WinComboBox = Me.UIТестированиеПОWindow.UINumericUpDown1Window.UINumericUpDown1ComboBox
            Dim uIОКButton As WinButton = Me.UIОКWindow.UIОКButton
            Dim uIПосчитатьWindow As WinWindow = Me.UIТестированиеПОWindow.UIТестированиеПОClient.UIПосчитатьWindow

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(114, 63))

            'Выберите "77" в "numericUpDown1" поле со списком
            uINumericUpDown1ComboBox.EditableItem = Me.RecordedMethod1Params.UINumericUpDown1ComboBoxEditableItem

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(67, 56))

            'Выберите "777" в "numericUpDown1" поле со списком
            uINumericUpDown1ComboBox.EditableItem = Me.RecordedMethod1Params.UINumericUpDown1ComboBoxEditableItem1

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(100, 61))

            'Выберите "7777" в "numericUpDown1" поле со списком
            uINumericUpDown1ComboBox.EditableItem = Me.RecordedMethod1Params.UINumericUpDown1ComboBoxEditableItem2

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(70, 49))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(70, 49))

            'Выберите "77776" в "numericUpDown1" поле со списком
            uINumericUpDown1ComboBox.EditableItem = Me.RecordedMethod1Params.UINumericUpDown1ComboBoxEditableItem3

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(72, 54))

            'Выберите "777768" в "numericUpDown1" поле со списком
            uINumericUpDown1ComboBox.EditableItem = Me.RecordedMethod1Params.UINumericUpDown1ComboBoxEditableItem4

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(65, 47))

            'Щелкните "ОК" кнопка
            Mouse.Click(uIОКButton, New Point(21, 18))

            'Выберите "77774" в "numericUpDown1" поле со списком
            uINumericUpDown1ComboBox.EditableItem = Me.RecordedMethod1Params.UINumericUpDown1ComboBoxEditableItem5

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(62, 51))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(99, 60))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(103, 41))

            'Щелкните "Ввести" окно
            Mouse.Click(uIВвестиWindow, New Point(103, 47))

            'Щелкните "Посчитать" окно
            Mouse.Click(uIПосчитатьWindow, New Point(115, 51))
        End Sub
        
        #Region "Properties"
        Public Overridable ReadOnly Property RecordedMethod1Params() As RecordedMethod1Params
            Get
                If (Me.mRecordedMethod1Params Is Nothing) Then
                    Me.mRecordedMethod1Params = New RecordedMethod1Params()
                End If
                Return Me.mRecordedMethod1Params
            End Get
        End Property
        
        Public ReadOnly Property UIТестированиеПОWindow() As UIТестированиеПОWindow
            Get
                If (Me.mUIТестированиеПОWindow Is Nothing) Then
                    Me.mUIТестированиеПОWindow = New UIТестированиеПОWindow()
                End If
                Return Me.mUIТестированиеПОWindow
            End Get
        End Property
        
        Public ReadOnly Property UIОКWindow() As UIОКWindow
            Get
                If (Me.mUIОКWindow Is Nothing) Then
                    Me.mUIОКWindow = New UIОКWindow()
                End If
                Return Me.mUIОКWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mRecordedMethod1Params As RecordedMethod1Params
        
        Private mUIТестированиеПОWindow As UIТестированиеПОWindow
        
        Private mUIОКWindow As UIОКWindow
        #End Region
    End Class
    
    '''<summary>
    '''Параметры для передачи в "RecordedMethod1"
    '''</summary>
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class RecordedMethod1Params
        
        #Region "Fields"
        '''<summary>
        '''Выберите "77" в "numericUpDown1" поле со списком
        '''</summary>
        Public UINumericUpDown1ComboBoxEditableItem As String = "77"
        
        '''<summary>
        '''Выберите "777" в "numericUpDown1" поле со списком
        '''</summary>
        Public UINumericUpDown1ComboBoxEditableItem1 As String = "777"
        
        '''<summary>
        '''Выберите "7777" в "numericUpDown1" поле со списком
        '''</summary>
        Public UINumericUpDown1ComboBoxEditableItem2 As String = "7777"
        
        '''<summary>
        '''Выберите "77776" в "numericUpDown1" поле со списком
        '''</summary>
        Public UINumericUpDown1ComboBoxEditableItem3 As String = "77776"
        
        '''<summary>
        '''Выберите "777768" в "numericUpDown1" поле со списком
        '''</summary>
        Public UINumericUpDown1ComboBoxEditableItem4 As String = "777768"
        
        '''<summary>
        '''Выберите "77774" в "numericUpDown1" поле со списком
        '''</summary>
        Public UINumericUpDown1ComboBoxEditableItem5 As String = "77774"
        #End Region
    End Class
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class UIТестированиеПОWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "Тестирование ПО"
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains))
            Me.WindowTitles.Add("Тестирование ПО")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIТестированиеПОClient() As UIТестированиеПОClient
            Get
                If (Me.mUIТестированиеПОClient Is Nothing) Then
                    Me.mUIТестированиеПОClient = New UIТестированиеПОClient(Me)
                End If
                Return Me.mUIТестированиеПОClient
            End Get
        End Property
        
        Public ReadOnly Property UINumericUpDown1Window() As UINumericUpDown1Window
            Get
                If (Me.mUINumericUpDown1Window Is Nothing) Then
                    Me.mUINumericUpDown1Window = New UINumericUpDown1Window(Me)
                End If
                Return Me.mUINumericUpDown1Window
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIТестированиеПОClient As UIТестированиеПОClient
        
        Private mUINumericUpDown1Window As UINumericUpDown1Window
        #End Region
    End Class
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class UIТестированиеПОClient
        Inherits WinClient
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinControl.PropertyNames.Name) = "Тестирование ПО"
            Me.WindowTitles.Add("Тестирование ПО")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIВвестиWindow() As WinWindow
            Get
                If (Me.mUIВвестиWindow Is Nothing) Then
                    Me.mUIВвестиWindow = New WinWindow(Me)
                    Me.mUIВвестиWindow.SearchProperties(WinWindow.PropertyNames.Name) = "Ввести"
                    Me.mUIВвестиWindow.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains))
                    Me.mUIВвестиWindow.WindowTitles.Add("Тестирование ПО")
                End If
                Return Me.mUIВвестиWindow
            End Get
        End Property
        
        Public ReadOnly Property UIПосчитатьWindow() As WinWindow
            Get
                If (Me.mUIПосчитатьWindow Is Nothing) Then
                    Me.mUIПосчитатьWindow = New WinWindow(Me)
                    Me.mUIПосчитатьWindow.SearchProperties(WinWindow.PropertyNames.Name) = "Посчитать"
                    Me.mUIПосчитатьWindow.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains))
                    Me.mUIПосчитатьWindow.WindowTitles.Add("Тестирование ПО")
                End If
                Return Me.mUIПосчитатьWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIВвестиWindow As WinWindow
        
        Private mUIПосчитатьWindow As WinWindow
        #End Region
    End Class
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class UINumericUpDown1Window
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlName) = "numericUpDown1"
            Me.WindowTitles.Add("Тестирование ПО")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UINumericUpDown1ComboBox() As WinComboBox
            Get
                If (Me.mUINumericUpDown1ComboBox Is Nothing) Then
                    Me.mUINumericUpDown1ComboBox = New WinComboBox(Me)
                    Me.mUINumericUpDown1ComboBox.WindowTitles.Add("Тестирование ПО")
                End If
                Return Me.mUINumericUpDown1ComboBox
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUINumericUpDown1ComboBox As WinComboBox
        #End Region
    End Class
    
    <GeneratedCode("Построитель кодированных тестов ИП", "16.0.29514.35")>  _
    Public Class UIОКWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "ОК"
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "Button"
            Me.WindowTitles.Add("ОК")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIОКButton() As WinButton
            Get
                If (Me.mUIОКButton Is Nothing) Then
                    Me.mUIОКButton = New WinButton(Me)
                    Me.mUIОКButton.SearchProperties(WinButton.PropertyNames.Name) = "ОК"
                    Me.mUIОКButton.WindowTitles.Add("ОК")
                End If
                Return Me.mUIОКButton
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIОКButton As WinButton
        #End Region
    End Class
End Namespace
